# Generated by Django 3.1.6 on 2021-05-26 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPaper', '0002_subscribers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscribers',
        ),
    ]
